### ISSUE TITLE
Some articles on vg.no not getting blocked.

### ISSUE THREAD

**Issue by bendiknesbo** [cf256/AvisPlussBlock#13]
Recently, some of the pluss-articles on vg.no has been slipping through. The following is the HTML for one of them.

`<div id="df-86-s9dc890f" class="article-extract article-extract-half right row-3 img-brd-1 bg-default df-right-in-row df-top-in-row df-bottom-in-row">
	
	<div class="article-content">
		<span class="df-img-container df-img-skin-pluss"><span class="df-img-container-inner" style="padding-bottom:71.835443%"><a href="http://pluss.vg.no/2017/12/13/3021/3021_24207885?row=3"><img src="https://vgc.no/drfront/images/2017/12/13/c=353,150,4296,3086;w=316;h=227;374410.jpg" alt="" title="Nesvold, Jon Olav" class="article-image lazy" data-src="https://vgc.no/drfront/images/2017/12/13/c=353,150,4296,3086;w=316;h=227;374410.jpg"><noscript>&lt;img src="https://vgc.no/drfront/images/2017/12/13/c=353,150,4296,3086;w=316;h=227;374410.jpg" alt="" title="Nesvold, Jon Olav" class="article-image"&gt;</noscript></a><span class="df-img-layer"><a href="http://pluss.vg.no/2017/12/13/3021/3021_24207885?row=3">&nbsp;</a></span></span></span>
<h3 class=" vg-fs52"><a href="http://pluss.vg.no/2017/12/13/3021/3021_24207885?row=3"><span class="vg-fs46"><span class="vg-fs52">Skattegrepene</span><br><span class="vg-fs47">du bør gjøre nå</span></span></a></h3>
<div class="clearer"></div>
	</div>
	
</div>`

**Comment by cf256** [comment]
Thanks for reporting! It should be fixed and updated in the Chrome Web Store within 60 minutes
