### ISSUE TITLE
Icon isn't updated immediately when resuming the extension

### ISSUE THREAD

**Issue by peterjohansen** [cf256/AvisPlussBlock#4]
To recreate:
1. Navigate to a web page where the extension will run
2. Pause it (the icon is updated instantly to reflect the change)
3. Resume it (the page has to be refreshed for the icon to change)

**Comment by cf256** [comment]
Hmm I am not able to recreate this.. On my end the icon is updated straight away.

**Comment by peterjohansen** [comment]
Weird. I just checked and I still have this problem. I suggest keeping the issue open for now.

**Comment by cf256** [comment]
If you have the inspector for the popup page open, the icon will not update I just noticed. Did you have the inspector open when this happened to you?

**Comment by cf256** [comment]
I think it is because the values stored in storage is only strings. I..e.      

``` javascript
var iconPath = (item.paused ? 'images/blokkpluss-paused-38.png' : 'images/blokkpluss-38.png');
```

always returned false because we compared strings and booleans. If we are to use boolean operators on the values stored in storage we need to use `JSON.parse(value)`.  Working on a fix now.
