### ISSUE TITLE
Mottiltak fra db.no?

### ISSUE THREAD

**Issue by dagbdagb** [cf256/AvisPlussBlock#5]
Versjon 0.5 later ikke til å hindre hverken annonsørinnhold eller 'pluss'-artikler fra db.no nå?

**Comment by cf256** [comment]
Rart. Den blokkerer artiklene hos meg. Kan du prøve å reinstallere utvidelsen?

**Comment by dagbdagb** [comment]
Det gjorde susen. Beklager falsk alarm.
